import type {
  AdjustmentType,
  Branch,
  CategoryStockPoint,
  InventoryItem,
  MovementTrendPoint,
  StockAdjustment,
  StockCountSession,
  StockMovement,
  StockTransfer,
  StockValuePoint,
  Warehouse,
} from "../types"

export const mockBranches: Branch[] = [
  { id: "branch-mm", name: "Myanmar Branch", warehouseIds: ["wh-yangon", "wh-mandalay"] },
  { id: "branch-th", name: "Thailand Branch", warehouseIds: ["wh-bangkok", "wh-chiangmai"] },
]

export const mockWarehouses: Warehouse[] = [
  {
    id: "wh-yangon",
    name: "Yangon Warehouse",
    code: "YGN-01",
    branchId: "branch-mm",
    branchName: "Myanmar Branch",
    address: "No. 42, Pyay Road, Yangon",
    manager: "Thida Win",
    contact: "+95 9 123 456 78",
    status: "active",
    totalProducts: 5,
    stockValue: 812500,
  },
  {
    id: "wh-mandalay",
    name: "Mandalay Warehouse",
    code: "MDY-01",
    branchId: "branch-mm",
    branchName: "Myanmar Branch",
    address: "26th Street, Mandalay",
    manager: "Kyaw Zin",
    contact: "+95 9 234 567 89",
    status: "active",
    totalProducts: 3,
    stockValue: 340000,
  },
  {
    id: "wh-bangkok",
    name: "Bangkok Warehouse",
    code: "BKK-01",
    branchId: "branch-th",
    branchName: "Thailand Branch",
    address: "Sukhumvit Rd, Bangkok",
    manager: "Somchai P.",
    contact: "+66 81 234 5678",
    status: "active",
    totalProducts: 4,
    stockValue: 976000,
  },
  {
    id: "wh-chiangmai",
    name: "Chiang Mai Warehouse",
    code: "CNX-01",
    branchId: "branch-th",
    branchName: "Thailand Branch",
    address: "Nimman Rd, Chiang Mai",
    manager: "Nattapong K.",
    contact: "+66 82 345 6789",
    status: "inactive",
    totalProducts: 1,
    stockValue: 45000,
  },
]

export const mockInventory: InventoryItem[] = [
  {
    id: "inv-1",
    productId: "prod-1",
    productName: "Nike Classic Tee",
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
    sku: "NIKE-TS-BLK-M-001",
    variantId: "var-1",
    color: "Black",
    size: "M",
    warehouseId: "wh-yangon",
    warehouseName: "Yangon Warehouse",
    availableQty: 120,
    reservedQty: 10,
    incomingQty: 50,
    reorderLevel: 30,
    overstockLevel: 300,
    unitCost: 20,
  },
  {
    id: "inv-2",
    productId: "prod-1",
    productName: "Nike Classic Tee",
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
    sku: "NIKE-TS-BLK-L-001",
    variantId: "var-2",
    color: "Black",
    size: "L",
    warehouseId: "wh-yangon",
    warehouseName: "Yangon Warehouse",
    availableQty: 18,
    reservedQty: 5,
    incomingQty: 0,
    reorderLevel: 20,
    overstockLevel: 300,
    unitCost: 20,
  },
  {
    id: "inv-3",
    productId: "prod-2",
    productName: "Floral Summer Dress",
    imageUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
    sku: "ZARA-FD-RED-S-014",
    variantId: "var-4",
    color: "Red",
    size: "S",
    warehouseId: "wh-bangkok",
    warehouseName: "Bangkok Warehouse",
    availableQty: 0,
    reservedQty: 0,
    incomingQty: 40,
    reorderLevel: 15,
    overstockLevel: 200,
    unitCost: 30,
  },
  {
    id: "inv-4",
    productId: "prod-3",
    productName: "Kids Graphic Tee",
    sku: "HM-KT-022",
    warehouseId: "wh-mandalay",
    warehouseName: "Mandalay Warehouse",
    availableQty: 450,
    reservedQty: 0,
    incomingQty: 0,
    reorderLevel: 30,
    overstockLevel: 400,
    unitCost: 8,
  },
  {
    id: "inv-5",
    productId: "prod-4",
    productName: "Leather Belt",
    imageUrl: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=400",
    sku: "GUESS-AC-007",
    warehouseId: "wh-yangon",
    warehouseName: "Yangon Warehouse",
    availableQty: 210,
    reservedQty: 0,
    incomingQty: 0,
    reorderLevel: 25,
    overstockLevel: 250,
    unitCost: 12,
  },
  {
    id: "inv-6",
    productId: "prod-5",
    productName: "Wool Blend Coat",
    imageUrl: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400",
    sku: "MANGO-WC-BLK-M-009",
    variantId: "var-6",
    color: "Black",
    size: "M",
    warehouseId: "wh-bangkok",
    warehouseName: "Bangkok Warehouse",
    availableQty: 18,
    reservedQty: 0,
    incomingQty: 0,
    reorderLevel: 10,
    overstockLevel: 100,
    unitCost: 60,
  },
]

const now = Date.now()
const daysAgo = (n: number) => new Date(now - n * 86400000).toISOString()

export const mockMovements: StockMovement[] = [
  {
    id: "mv-1",
    date: daysAgo(1),
    type: "purchase_receipt",
    reference: "PR-2026-0142",
    productId: "prod-1",
    productName: "Nike Classic Tee",
    sku: "NIKE-TS-BLK-M-001",
    variantLabel: "Black / M",
    warehouseId: "wh-yangon",
    warehouseName: "Yangon Warehouse",
    qtyBefore: 70,
    qtyChange: 50,
    qtyAfter: 120,
    user: "Warehouse Staff",
  },
  {
    id: "mv-2",
    date: daysAgo(2),
    type: "sales_delivery",
    reference: "INV-2026-3301",
    productId: "prod-4",
    productName: "Leather Belt",
    sku: "GUESS-AC-007",
    warehouseId: "wh-yangon",
    warehouseName: "Yangon Warehouse",
    qtyBefore: 215,
    qtyChange: -5,
    qtyAfter: 210,
    user: "Cashier",
  },
  {
    id: "mv-3",
    date: daysAgo(3),
    type: "stock_transfer",
    reference: "TRF-2026-0021",
    productId: "prod-5",
    productName: "Wool Blend Coat",
    sku: "MANGO-WC-BLK-M-009",
    variantLabel: "Black / M",
    warehouseId: "wh-bangkok",
    warehouseName: "Bangkok Warehouse",
    qtyBefore: 8,
    qtyChange: 10,
    qtyAfter: 18,
    user: "Manager",
  },
  {
    id: "mv-4",
    date: daysAgo(4),
    type: "stock_adjustment",
    reference: "ADJ-2026-0009",
    productId: "prod-1",
    productName: "Nike Classic Tee",
    sku: "NIKE-TS-BLK-L-001",
    variantLabel: "Black / L",
    warehouseId: "wh-yangon",
    warehouseName: "Yangon Warehouse",
    qtyBefore: 20,
    qtyChange: -2,
    qtyAfter: 18,
    user: "Inventory Controller",
  },
  {
    id: "mv-5",
    date: daysAgo(5),
    type: "return",
    reference: "RTN-2026-0011",
    productId: "prod-2",
    productName: "Floral Summer Dress",
    sku: "ZARA-FD-RED-S-014",
    variantLabel: "Red / S",
    warehouseId: "wh-bangkok",
    warehouseName: "Bangkok Warehouse",
    qtyBefore: 0,
    qtyChange: 0,
    qtyAfter: 0,
    user: "Cashier",
  },
  {
    id: "mv-6",
    date: daysAgo(6),
    type: "damage",
    reference: "DMG-2026-0004",
    productId: "prod-3",
    productName: "Kids Graphic Tee",
    sku: "HM-KT-022",
    warehouseId: "wh-mandalay",
    warehouseName: "Mandalay Warehouse",
    qtyBefore: 455,
    qtyChange: -5,
    qtyAfter: 450,
    user: "Warehouse Staff",
  },
  {
    id: "mv-7",
    date: daysAgo(10),
    type: "opening_stock",
    reference: "OPEN-2026-0001",
    productId: "prod-3",
    productName: "Kids Graphic Tee",
    sku: "HM-KT-022",
    warehouseId: "wh-mandalay",
    warehouseName: "Mandalay Warehouse",
    qtyBefore: 0,
    qtyChange: 460,
    qtyAfter: 460,
    user: "Admin",
  },
]

export const mockTransfers: StockTransfer[] = [
  {
    id: "trf-1",
    reference: "TRF-2026-0021",
    fromWarehouseId: "wh-yangon",
    fromWarehouseName: "Yangon Warehouse",
    toWarehouseId: "wh-bangkok",
    toWarehouseName: "Bangkok Warehouse",
    status: "completed",
    items: [
      {
        id: "line-1",
        productId: "prod-5",
        productName: "Wool Blend Coat",
        sku: "MANGO-WC-BLK-M-009",
        variantLabel: "Black / M",
        availableQty: 18,
        transferQty: 10,
      },
    ],
    createdBy: "Cashier",
    createdAt: daysAgo(4),
    approvedBy: "Manager",
    approvedAt: daysAgo(3),
  },
  {
    id: "trf-2",
    reference: "TRF-2026-0022",
    fromWarehouseId: "wh-mandalay",
    fromWarehouseName: "Mandalay Warehouse",
    toWarehouseId: "wh-yangon",
    toWarehouseName: "Yangon Warehouse",
    status: "pending_approval",
    items: [
      {
        id: "line-2",
        productId: "prod-3",
        productName: "Kids Graphic Tee",
        sku: "HM-KT-022",
        availableQty: 450,
        transferQty: 100,
      },
    ],
    createdBy: "Warehouse Staff",
    createdAt: daysAgo(1),
  },
  {
    id: "trf-3",
    reference: "TRF-2026-0023",
    fromWarehouseId: "wh-bangkok",
    fromWarehouseName: "Bangkok Warehouse",
    toWarehouseId: "wh-chiangmai",
    toWarehouseName: "Chiang Mai Warehouse",
    status: "draft",
    items: [],
    createdBy: "Warehouse Staff",
    createdAt: daysAgo(0),
  },
]

export const mockAdjustments: StockAdjustment[] = [
  {
    id: "adj-1",
    reference: "ADJ-2026-0009",
    warehouseId: "wh-yangon",
    warehouseName: "Yangon Warehouse",
    productId: "prod-1",
    productName: "Nike Classic Tee",
    sku: "NIKE-TS-BLK-L-001",
    variantLabel: "Black / L",
    currentQty: 20,
    adjustedQty: 18,
    difference: -2,
    type: "stock_count_difference" as AdjustmentType,
    reason: "Physical count variance during monthly stock count",
    status: "approved",
    createdBy: "Inventory Controller",
    createdAt: daysAgo(4),
  },
  {
    id: "adj-2",
    reference: "ADJ-2026-0010",
    warehouseId: "wh-mandalay",
    warehouseName: "Mandalay Warehouse",
    productId: "prod-3",
    productName: "Kids Graphic Tee",
    sku: "HM-KT-022",
    currentQty: 455,
    adjustedQty: 450,
    difference: -5,
    type: "damaged_product",
    reason: "Water damage during storage",
    status: "pending",
    createdBy: "Warehouse Staff",
    createdAt: daysAgo(1),
  },
]

export const mockStockCounts: StockCountSession[] = [
  {
    id: "count-1",
    reference: "CNT-2026-0005",
    warehouseId: "wh-yangon",
    warehouseName: "Yangon Warehouse",
    createdAt: daysAgo(1),
    status: "in_progress",
    lines: [
      {
        id: "line-1",
        productId: "prod-1",
        productName: "Nike Classic Tee",
        sku: "NIKE-TS-BLK-M-001",
        variantLabel: "Black / M",
        systemQty: 120,
        countedQty: 118,
        difference: -2,
        status: "pending",
      },
      {
        id: "line-2",
        productId: "prod-4",
        productName: "Leather Belt",
        sku: "GUESS-AC-007",
        systemQty: 210,
        countedQty: 210,
        difference: 0,
        status: "reviewed",
      },
      {
        id: "line-3",
        productId: "prod-1",
        productName: "Nike Classic Tee",
        sku: "NIKE-TS-BLK-L-001",
        variantLabel: "Black / L",
        systemQty: 18,
        countedQty: null,
        difference: 0,
        status: "pending",
      },
    ],
  },
]

export const stockValueByWarehouse: StockValuePoint[] = mockWarehouses.map((w) => ({
  warehouse: w.name,
  value: w.stockValue,
}))

export const categoryStockDistribution: CategoryStockPoint[] = [
  { category: "Men", quantity: 340 },
  { category: "Women", quantity: 63 },
  { category: "Kids", quantity: 450 },
  { category: "Accessories", quantity: 210 },
]

export const movementTrend: MovementTrendPoint[] = [
  { period: "Mon", incoming: 120, outgoing: 80 },
  { period: "Tue", incoming: 60, outgoing: 95 },
  { period: "Wed", incoming: 90, outgoing: 70 },
  { period: "Thu", incoming: 40, outgoing: 110 },
  { period: "Fri", incoming: 150, outgoing: 60 },
  { period: "Sat", incoming: 30, outgoing: 130 },
  { period: "Sun", incoming: 20, outgoing: 40 },
]
