import type {
  AttributeOption,
  Brand,
  Category,
  Collection,
  Product,
  ProductListItem,
} from "../types"

export const mockCategories: Category[] = [
  { id: "cat-fashion", name: "Fashion", parentId: null, isActive: true, productCount: 5 },
  { id: "cat-men", name: "Men", parentId: "cat-fashion", isActive: true, productCount: 2 },
  { id: "cat-men-shirts", name: "Shirts", parentId: "cat-men", isActive: true, productCount: 1 },
  { id: "cat-men-pants", name: "Pants", parentId: "cat-men", isActive: true, productCount: 1 },
  { id: "cat-women", name: "Women", parentId: "cat-fashion", isActive: true, productCount: 2 },
  { id: "cat-women-dresses", name: "Dresses", parentId: "cat-women", isActive: true, productCount: 1 },
  { id: "cat-women-skirts", name: "Skirts", parentId: "cat-women", isActive: true, productCount: 1 },
  { id: "cat-kids", name: "Kids", parentId: "cat-fashion", isActive: true, productCount: 1 },
  { id: "cat-accessories", name: "Accessories", parentId: null, isActive: true, productCount: 1 },
]

export const mockBrands: Brand[] = [
  { id: "brand-nike", name: "Nike", country: "USA", description: "Sportswear and athletic apparel.", isActive: true, productCount: 1 },
  { id: "brand-zara", name: "Zara", country: "Spain", description: "Fast fashion retailer.", isActive: true, productCount: 1 },
  { id: "brand-hm", name: "H&M", country: "Sweden", description: "Affordable fashion for all.", isActive: true, productCount: 1 },
  { id: "brand-guess", name: "Guess", country: "USA", description: "Premium denim and accessories.", isActive: true, productCount: 1 },
  { id: "brand-mango", name: "Mango", country: "Spain", description: "Contemporary women's fashion.", isActive: true, productCount: 1 },
]

export const mockCollections: Collection[] = [
  { id: "col-ss26", name: "Spring Collection 2026", season: "spring_summer", year: 2026, isActive: true, productCount: 2 },
  { id: "col-su26", name: "Summer Collection 2026", season: "spring_summer", year: 2026, isActive: true, productCount: 1 },
  { id: "col-wi26", name: "Winter Collection 2026", season: "autumn_winter", year: 2026, isActive: true, productCount: 2 },
]

export const attributeOptions: AttributeOption[] = [
  { id: "size-xs", kind: "size", value: "XS" },
  { id: "size-s", kind: "size", value: "S" },
  { id: "size-m", kind: "size", value: "M" },
  { id: "size-l", kind: "size", value: "L" },
  { id: "size-xl", kind: "size", value: "XL" },
  { id: "size-xxl", kind: "size", value: "XXL" },
  { id: "color-black", kind: "color", value: "Black", swatch: "#0a0a0a" },
  { id: "color-white", kind: "color", value: "White", swatch: "#fafafa" },
  { id: "color-red", kind: "color", value: "Red", swatch: "#dc2626" },
  { id: "color-blue", kind: "color", value: "Blue", swatch: "#2563eb" },
  { id: "style-slim", kind: "style", value: "Slim Fit" },
  { id: "style-regular", kind: "style", value: "Regular Fit" },
  { id: "style-oversize", kind: "style", value: "Oversize" },
  { id: "material-cotton", kind: "material", value: "Cotton" },
  { id: "material-denim", kind: "material", value: "Denim" },
  { id: "material-leather", kind: "material", value: "Leather" },
]

const now = new Date().toISOString()

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "Nike Classic Tee",
    type: "variant",
    categoryId: "cat-men-shirts",
    categoryName: "Shirts",
    brandId: "brand-nike",
    brandName: "Nike",
    collectionId: "col-ss26",
    collectionName: "Spring Collection 2026",
    description: "A comfortable cotton crew-neck tee with the classic Nike swoosh.",
    season: "spring_summer",
    gender: "men",
    sku: "NIKE-TS-001",
    status: "active",
    images: [
      { id: "img-1", url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400", isPrimary: true, sortOrder: 0 },
      { id: "img-2", url: "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=400", isPrimary: false, sortOrder: 1 },
    ],
    variants: [
      { id: "var-1", productId: "prod-1", sku: "NIKE-TS-BLK-M-001", barcode: "890001000001", attributes: { color: "Black", size: "M" }, costPrice: 20, sellingPrice: 35, stockQuantity: 120, status: "active" },
      { id: "var-2", productId: "prod-1", sku: "NIKE-TS-BLK-L-001", barcode: "890001000002", attributes: { color: "Black", size: "L" }, costPrice: 20, sellingPrice: 35, stockQuantity: 80, status: "active" },
      { id: "var-3", productId: "prod-1", sku: "NIKE-TS-WHT-M-001", barcode: "890001000003", attributes: { color: "White", size: "M" }, costPrice: 20, sellingPrice: 35, stockQuantity: 45, status: "active" },
    ],
    pricing: { costPrice: 20, sellingPrice: 35, discountPrice: 30, taxRate: 8 },
    stockQuantity: 245,
    warehouseStock: [
      { warehouseId: "wh-central", warehouseName: "Central Warehouse", available: 120, reserved: 10, incoming: 50 },
      { warehouseId: "wh-north", warehouseName: "North Branch", available: 60, reserved: 5, incoming: 0 },
    ],
    history: [
      { id: "h-1", action: "Created", detail: "Product created", actor: "Admin", timestamp: now },
      { id: "h-2", action: "Stock adjusted", detail: "+50 units received", actor: "Warehouse Staff", timestamp: now },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-2",
    name: "Floral Summer Dress",
    type: "variant",
    categoryId: "cat-women-dresses",
    categoryName: "Dresses",
    brandId: "brand-zara",
    brandName: "Zara",
    collectionId: "col-su26",
    collectionName: "Summer Collection 2026",
    description: "Lightweight floral dress, perfect for warm weather.",
    season: "spring_summer",
    gender: "women",
    sku: "ZARA-FD-014",
    status: "active",
    images: [
      { id: "img-3", url: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400", isPrimary: true, sortOrder: 0 },
    ],
    variants: [
      { id: "var-4", productId: "prod-2", sku: "ZARA-FD-RED-S-014", barcode: "890002000001", attributes: { color: "Red", size: "S" }, costPrice: 30, sellingPrice: 68, stockQuantity: 25, status: "active" },
      { id: "var-5", productId: "prod-2", sku: "ZARA-FD-RED-M-014", barcode: "890002000002", attributes: { color: "Red", size: "M" }, costPrice: 30, sellingPrice: 68, stockQuantity: 20, status: "active" },
    ],
    pricing: { costPrice: 30, sellingPrice: 68, taxRate: 8 },
    stockQuantity: 45,
    warehouseStock: [
      { warehouseId: "wh-central", warehouseName: "Central Warehouse", available: 45, reserved: 3, incoming: 0 },
    ],
    history: [{ id: "h-3", action: "Created", detail: "Product created", actor: "Admin", timestamp: now }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-3",
    name: "Kids Graphic Tee",
    type: "simple",
    categoryId: "cat-kids",
    categoryName: "Kids",
    brandId: "brand-hm",
    brandName: "H&M",
    description: "Fun graphic print tee for kids.",
    season: "all_season",
    gender: "kids",
    sku: "HM-KT-022",
    status: "draft",
    images: [],
    variants: [],
    pricing: { costPrice: 8, sellingPrice: 15, taxRate: 8 },
    stockQuantity: 0,
    warehouseStock: [],
    history: [{ id: "h-4", action: "Created", detail: "Product created as draft", actor: "Manager", timestamp: now }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-4",
    name: "Leather Belt",
    type: "simple",
    categoryId: "cat-accessories",
    categoryName: "Accessories",
    brandId: "brand-guess",
    brandName: "Guess",
    description: "Genuine leather belt with metal buckle.",
    season: "all_season",
    gender: "unisex",
    sku: "GUESS-AC-007",
    status: "active",
    images: [
      { id: "img-4", url: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=400", isPrimary: true, sortOrder: 0 },
    ],
    variants: [],
    pricing: { costPrice: 12, sellingPrice: 25, taxRate: 8 },
    stockQuantity: 210,
    warehouseStock: [
      { warehouseId: "wh-central", warehouseName: "Central Warehouse", available: 210, reserved: 0, incoming: 0 },
    ],
    history: [{ id: "h-5", action: "Created", detail: "Product created", actor: "Admin", timestamp: now }],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-5",
    name: "Wool Blend Coat",
    type: "variant",
    categoryId: "cat-women",
    categoryName: "Women",
    brandId: "brand-mango",
    brandName: "Mango",
    collectionId: "col-wi26",
    collectionName: "Winter Collection 2026",
    description: "Warm wool-blend coat for the cold season.",
    season: "autumn_winter",
    gender: "women",
    sku: "MANGO-WC-009",
    status: "archived",
    images: [
      { id: "img-5", url: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400", isPrimary: true, sortOrder: 0 },
    ],
    variants: [
      { id: "var-6", productId: "prod-5", sku: "MANGO-WC-BLK-M-009", barcode: "890005000001", attributes: { color: "Black", size: "M" }, costPrice: 60, sellingPrice: 129, stockQuantity: 18, status: "inactive" },
    ],
    pricing: { costPrice: 60, sellingPrice: 129, taxRate: 8 },
    stockQuantity: 18,
    warehouseStock: [
      { warehouseId: "wh-central", warehouseName: "Central Warehouse", available: 18, reserved: 0, incoming: 0 },
    ],
    history: [{ id: "h-6", action: "Archived", detail: "Season ended", actor: "Manager", timestamp: now }],
    createdAt: now,
    updatedAt: now,
  },
]

export function toListItem(product: Product): ProductListItem {
  return {
    id: product.id,
    imageUrl: product.images.find((i) => i.isPrimary)?.url ?? product.images[0]?.url,
    name: product.name,
    sku: product.sku,
    categoryName: product.categoryName,
    brandName: product.brandName,
    variantCount: product.variants.length,
    stockQuantity: product.stockQuantity,
    sellingPrice: product.pricing.sellingPrice,
    status: product.status,
    createdAt: product.createdAt,
  }
}
