import type {
  Customer,
  CustomerAnalytics,
  DiscountRule,
  LoyaltyTransaction,
  ProductPerformancePoint,
  RevenueTrendPoint,
  SalesInvoice,
  SalesOrder,
  SalesReturn,
} from "../types"

const now = Date.now()
const daysAgo = (n: number) => new Date(now - n * 86400000).toISOString()
const daysFromNow = (n: number) => new Date(now + n * 86400000).toISOString()

export const mockCustomers: Customer[] = [
  {
    id: "cust-1",
    name: "Aye Chan Moe",
    gender: "female",
    birthday: "1994-03-12",
    phone: "+95 9 111 222 33",
    email: "ayechanmoe@example.com",
    country: "Myanmar",
    city: "Yangon",
    address: "123 Bogyoke Rd, Yangon",
    customerGroup: "VIP",
    loyaltyMember: true,
    memberLevel: "gold",
    preferredSize: "M",
    preferredBrand: "Zara",
    totalOrders: 24,
    totalSpending: 3250,
    loyaltyPoints: 480,
    status: "active",
    createdAt: daysAgo(400),
  },
  {
    id: "cust-2",
    name: "Kyaw Zin Htet",
    gender: "male",
    birthday: "1989-07-22",
    phone: "+95 9 222 333 44",
    email: "kyawzinhtet@example.com",
    country: "Myanmar",
    city: "Mandalay",
    address: "45 26th Street, Mandalay",
    customerGroup: "Regular",
    loyaltyMember: true,
    memberLevel: "silver",
    preferredSize: "L",
    preferredBrand: "Nike",
    totalOrders: 9,
    totalSpending: 890,
    loyaltyPoints: 89,
    status: "active",
    createdAt: daysAgo(220),
  },
  {
    id: "cust-3",
    name: "Su Su Aung",
    gender: "female",
    phone: "+95 9 333 444 55",
    email: "susuaung@example.com",
    country: "Myanmar",
    city: "Yangon",
    address: "78 Pyay Road, Yangon",
    customerGroup: "Regular",
    loyaltyMember: false,
    memberLevel: "bronze",
    totalOrders: 2,
    totalSpending: 145,
    loyaltyPoints: 0,
    status: "active",
    createdAt: daysAgo(30),
  },
  {
    id: "cust-4",
    name: "Min Thu",
    gender: "male",
    phone: "+95 9 444 555 66",
    email: "minthu@example.com",
    country: "Thailand",
    city: "Bangkok",
    address: "12 Sukhumvit Rd, Bangkok",
    customerGroup: "VIP",
    loyaltyMember: true,
    memberLevel: "platinum",
    preferredSize: "M",
    preferredBrand: "Guess",
    totalOrders: 41,
    totalSpending: 6120,
    loyaltyPoints: 980,
    status: "active",
    createdAt: daysAgo(600),
  },
  {
    id: "cust-5",
    name: "Thanda Win",
    gender: "female",
    phone: "+95 9 555 666 77",
    email: "thandawin@example.com",
    country: "Myanmar",
    city: "Yangon",
    address: "9 Kaba Aye Pagoda Rd, Yangon",
    customerGroup: "Regular",
    loyaltyMember: false,
    memberLevel: "bronze",
    totalOrders: 1,
    totalSpending: 68,
    loyaltyPoints: 0,
    status: "inactive",
    createdAt: daysAgo(90),
  },
]

export const mockCustomerAnalytics: Record<string, CustomerAnalytics> = {
  "cust-1": {
    totalPurchase: 3250,
    averageOrderValue: 135.4,
    lastPurchaseDate: daysAgo(3),
    favoriteCategories: ["Women", "Accessories"],
    favoriteBrands: ["Zara", "Mango"],
  },
  "cust-2": {
    totalPurchase: 890,
    averageOrderValue: 98.9,
    lastPurchaseDate: daysAgo(10),
    favoriteCategories: ["Men"],
    favoriteBrands: ["Nike"],
  },
  "cust-3": {
    totalPurchase: 145,
    averageOrderValue: 72.5,
    lastPurchaseDate: daysAgo(20),
    favoriteCategories: ["Women"],
    favoriteBrands: ["Zara"],
  },
  "cust-4": {
    totalPurchase: 6120,
    averageOrderValue: 149.3,
    lastPurchaseDate: daysAgo(1),
    favoriteCategories: ["Men", "Accessories"],
    favoriteBrands: ["Guess", "Nike"],
  },
  "cust-5": {
    totalPurchase: 68,
    averageOrderValue: 68,
    lastPurchaseDate: daysAgo(90),
    favoriteCategories: ["Women"],
    favoriteBrands: ["H&M"],
  },
}

export const mockSalesOrders: SalesOrder[] = [
  {
    id: "so-1",
    orderNumber: "SO-2026-0410",
    customerId: "cust-1",
    customerName: "Aye Chan Moe",
    items: [
      {
        id: "soi-1",
        productId: "prod-2",
        productName: "Floral Summer Dress",
        sku: "ZARA-FD-RED-S-014",
        color: "Red",
        size: "S",
        quantity: 2,
        price: 68,
        discount: 10,
        tax: 10.88,
        total: 144.88,
      },
    ],
    deliveryDate: daysFromNow(5),
    paymentTerms: "Due on delivery",
    status: "processing",
    subtotal: 136,
    discountTotal: 10,
    taxTotal: 10.88,
    grandTotal: 136.88,
    createdAt: daysAgo(3),
  },
  {
    id: "so-2",
    orderNumber: "SO-2026-0411",
    customerId: "cust-4",
    customerName: "Min Thu",
    items: [
      {
        id: "soi-2",
        productId: "prod-5",
        productName: "Wool Blend Coat",
        sku: "MANGO-WC-BLK-M-009",
        color: "Black",
        size: "M",
        quantity: 1,
        price: 129,
        discount: 0,
        tax: 10.32,
        total: 139.32,
      },
    ],
    deliveryDate: daysFromNow(2),
    paymentTerms: "Prepaid",
    status: "confirmed",
    subtotal: 129,
    discountTotal: 0,
    taxTotal: 10.32,
    grandTotal: 139.32,
    createdAt: daysAgo(1),
  },
  {
    id: "so-3",
    orderNumber: "SO-2026-0409",
    customerId: "cust-2",
    customerName: "Kyaw Zin Htet",
    items: [
      {
        id: "soi-3",
        productId: "prod-1",
        productName: "Nike Classic Tee",
        sku: "NIKE-TS-BLK-L-001",
        color: "Black",
        size: "L",
        quantity: 3,
        price: 35,
        discount: 5,
        tax: 8,
        total: 108,
      },
    ],
    deliveryDate: daysAgo(2),
    paymentTerms: "Due on delivery",
    status: "delivered",
    subtotal: 105,
    discountTotal: 5,
    taxTotal: 8,
    grandTotal: 108,
    createdAt: daysAgo(9),
  },
]

export const mockInvoices: SalesInvoice[] = [
  {
    id: "sinv-1",
    invoiceNumber: "SINV-2026-1201",
    date: daysAgo(3),
    customerId: "cust-1",
    customerName: "Aye Chan Moe",
    salesPerson: "Cashier",
    items: mockSalesOrders[0].items,
    subtotal: 136,
    discountTotal: 10,
    taxTotal: 10.88,
    grandTotal: 136.88,
    amountPaid: 136.88,
    paymentMethod: "card",
    paymentStatus: "paid",
    status: "closed",
  },
  {
    id: "sinv-2",
    invoiceNumber: "SINV-2026-1202",
    date: daysAgo(1),
    customerId: "cust-4",
    customerName: "Min Thu",
    salesPerson: "Sales Associate",
    items: mockSalesOrders[1].items,
    subtotal: 129,
    discountTotal: 0,
    taxTotal: 10.32,
    grandTotal: 139.32,
    amountPaid: 70,
    paymentMethod: "bank_transfer",
    paymentStatus: "partial",
    status: "open",
  },
  {
    id: "sinv-3",
    invoiceNumber: "SINV-2026-1195",
    date: daysAgo(9),
    customerId: "cust-2",
    customerName: "Kyaw Zin Htet",
    salesPerson: "Cashier",
    items: mockSalesOrders[2].items,
    subtotal: 105,
    discountTotal: 5,
    taxTotal: 8,
    grandTotal: 108,
    amountPaid: 108,
    paymentMethod: "cash",
    paymentStatus: "paid",
    status: "closed",
  },
  {
    id: "sinv-4",
    invoiceNumber: "SINV-2026-1180",
    date: daysAgo(15),
    customerId: "cust-3",
    customerName: "Su Su Aung",
    salesPerson: "Cashier",
    items: [
      {
        id: "sinvi-1",
        productId: "prod-4",
        productName: "Leather Belt",
        sku: "GUESS-AC-007",
        quantity: 1,
        price: 25,
        discount: 0,
        tax: 2,
        total: 27,
      },
    ],
    subtotal: 25,
    discountTotal: 0,
    taxTotal: 2,
    grandTotal: 27,
    amountPaid: 0,
    paymentMethod: "cash",
    paymentStatus: "unpaid",
    status: "open",
  },
]

export const mockReturns: SalesReturn[] = [
  {
    id: "sret-1",
    reference: "RTN-S-2026-0044",
    invoiceId: "sinv-3",
    invoiceNumber: "SINV-2026-1195",
    customerId: "cust-2",
    customerName: "Kyaw Zin Htet",
    type: "product_return",
    reason: "Wrong size received",
    refundMethod: "cash",
    status: "approved",
    items: [
      {
        id: "sreti-1",
        productId: "prod-1",
        productName: "Nike Classic Tee",
        sku: "NIKE-TS-BLK-L-001",
        color: "Black",
        size: "L",
        purchasedQty: 3,
        returnQty: 1,
        unitPrice: 35,
      },
    ],
    refundAmount: 35,
    createdAt: daysAgo(6),
  },
]

export const mockDiscountRules: DiscountRule[] = [
  { id: "disc-1", name: "Nike Classic Tee — Launch Discount", kind: "product", target: "Nike Classic Tee", percent: 10, isActive: true },
  { id: "disc-2", name: "Women Category Sale", kind: "category", target: "Women", percent: 20, isActive: true },
  { id: "disc-3", name: "VIP Customer Discount", kind: "customer", target: "VIP", percent: 15, isActive: true },
  {
    id: "disc-4",
    name: "Summer Sale 2026",
    kind: "campaign",
    target: "Storewide",
    percent: 30,
    isActive: true,
    startDate: daysAgo(5),
    endDate: daysFromNow(25),
  },
  { id: "disc-5", name: "Winter Clearance 2025", kind: "campaign", target: "Storewide", percent: 40, isActive: false },
]

export const mockLoyaltyTransactions: LoyaltyTransaction[] = [
  { id: "loy-1", customerId: "cust-1", type: "earn", points: 14, reference: "SINV-2026-1201", date: daysAgo(3) },
  { id: "loy-2", customerId: "cust-1", type: "redeem", points: -100, reference: "SINV-2026-1150", date: daysAgo(45) },
  { id: "loy-3", customerId: "cust-4", type: "earn", points: 14, reference: "SINV-2026-1202", date: daysAgo(1) },
  { id: "loy-4", customerId: "cust-2", type: "earn", points: 11, reference: "SINV-2026-1195", date: daysAgo(9) },
]

export const revenueTrendByGranularity = {
  daily: [
    { period: "Mon", revenue: 4200 },
    { period: "Tue", revenue: 3800 },
    { period: "Wed", revenue: 5100 },
    { period: "Thu", revenue: 4600 },
    { period: "Fri", revenue: 6200 },
    { period: "Sat", revenue: 7400 },
    { period: "Sun", revenue: 5900 },
  ] as RevenueTrendPoint[],
  weekly: [
    { period: "Week 1", revenue: 28500 },
    { period: "Week 2", revenue: 31200 },
    { period: "Week 3", revenue: 27800 },
    { period: "Week 4", revenue: 33900 },
  ] as RevenueTrendPoint[],
  monthly: [
    { period: "Feb", revenue: 98000 },
    { period: "Mar", revenue: 105000 },
    { period: "Apr", revenue: 112000 },
    { period: "May", revenue: 108500 },
    { period: "Jun", revenue: 121000 },
    { period: "Jul", revenue: 118400 },
  ] as RevenueTrendPoint[],
  yearly: [
    { period: "2023", revenue: 980000 },
    { period: "2024", revenue: 1120000 },
    { period: "2025", revenue: 1340000 },
    { period: "2026", revenue: 742000 },
  ] as RevenueTrendPoint[],
}

export const productPerformance: ProductPerformancePoint[] = [
  { productName: "Nike Classic Tee", unitsSold: 320, revenue: 11200, profitMargin: 42.9 },
  { productName: "Floral Summer Dress", unitsSold: 145, revenue: 9860, profitMargin: 55.9 },
  { productName: "Leather Belt", unitsSold: 210, revenue: 5250, profitMargin: 52 },
  { productName: "Wool Blend Coat", unitsSold: 38, revenue: 4902, profitMargin: 53.5 },
  { productName: "Kids Graphic Tee", unitsSold: 12, revenue: 180, profitMargin: 46.7 },
]

export const customerAnalyticsSummary = {
  newCustomers: 18,
  returningCustomers: 64,
  customerLifetimeValue: 890,
}
