import {
  LayoutDashboard,
  ShoppingCart,
  ShoppingBag,
  Receipt,
  Undo2,
  Shirt,
  Tags,
  Award,
  Ruler,
  Palette,
  Warehouse,
  Boxes,
  ArrowLeftRight,
  ClipboardList,
  ClipboardCheck,
  ScanBarcode,
  FileBarChart,
  Truck,
  Building2,
  FileText,
  PackageCheck,
  FileSpreadsheet,
  Wallet,
  Undo2 as ReturnIcon,
  Users,
  Tag,
  Gift,
  BarChart3,
  LineChart,
  Package,
  Landmark,
  CalendarClock,
  BookOpen,
  ScrollText,
  HandCoins,
  ReceiptText,
  Percent,
  FileBarChart2,
  History,
  Settings,
  UserCog,
  Network,
  Building,
  CalendarCheck,
  Clock,
  CalendarRange,
  Banknote,
  UserCircle,
  Target,
  ShieldCheck,
  Lock,
  KeyRound,
  Workflow,
  BellRing,
  Store,
  Plug,
} from "lucide-react"
import type { NavItem } from "@/types/navigation"

/**
 * Single source of truth for the sidebar's navigation tree.
 * `module` maps each item to a permission-module key (types/user.ts) —
 * the Sidebar component filters this tree against the current user's
 * permissions before rendering, per Design System §4's "omission over
 * denial" rule: a user without access simply never sees the item.
 */
export const navigationTree: NavItem[] = [
  {
    // No "dashboard" backend resource exists — GET /reports/dashboard is
    // gated by permission reports.dashboard.read (resource "reports").
    label: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
    module: "reports",
    requiredAction: "view",
  },
  {
    label: "Sales",
    icon: Receipt,
    module: ["sales", "customers"],
    requiredAction: "view",
    children: [
      { label: "Dashboard", href: "/dashboard/sales", icon: LayoutDashboard, module: "sales", requiredAction: "view" },
      // No "pos" backend resource — POS checkout is just sales.create (+
      // payments.create for the payment step).
      { label: "POS", href: "/dashboard/sales/pos", icon: ShoppingCart, module: "sales", requiredAction: "create" },
      { label: "Sales Orders", href: "/dashboard/sales/orders", icon: ClipboardList, module: "sales", requiredAction: "view" },
      { label: "Online Orders", href: "/dashboard/sales/online-orders", icon: ShoppingBag, module: "sales", requiredAction: "view" },
      { label: "Omnichannel / Social", href: "/dashboard/sales/channels", icon: Store, module: "sales", requiredAction: "view" },
      { label: "Sales Invoice", href: "/dashboard/sales/invoices", icon: Receipt, module: "sales", requiredAction: "view" },
      { label: "Customers", href: "/dashboard/sales/customers", icon: Users, module: "customers", requiredAction: "view" },
      { label: "Returns", href: "/dashboard/sales/returns", icon: Undo2, module: "sales_returns", requiredAction: "edit" },
      { label: "Discounts", href: "/dashboard/sales/discounts", icon: Tag, module: "promotions", requiredAction: "view" },
      { label: "Loyalty", href: "/dashboard/sales/loyalty", icon: Gift, module: "loyalty", requiredAction: "view" },
      { label: "Reports", href: "/dashboard/sales/reports", icon: FileBarChart, module: "reports", requiredAction: "view" },
    ],
  },
  {
    label: "Products",
    icon: Shirt,
    module: ["products", "uoms", "product_variant_uoms", "price_lists", "price_list_items"],
    requiredAction: "view",
    children: [
      { label: "Product Master", href: "/dashboard/products", icon: Shirt, module: "products", requiredAction: "view" },
      { label: "Category", href: "/dashboard/products/categories", icon: Tags, module: "products", requiredAction: "view" },
      { label: "Brand", href: "/dashboard/products/brands", icon: Award, module: "products", requiredAction: "view" },
      { label: "UOM", href: "/dashboard/products/uoms", icon: Ruler, module: "uoms", requiredAction: "view" },
      { label: "Price Lists", href: "/dashboard/products/price-lists", icon: FileSpreadsheet, module: "price_lists", requiredAction: "view" },
      { label: "Size", href: "/dashboard/products/sizes", icon: Ruler, module: "products", requiredAction: "view" },
      { label: "Color", href: "/dashboard/products/colors", icon: Palette, module: "products", requiredAction: "view" },
      { label: "Variant", href: "/dashboard/products/variants", icon: Boxes, module: "products", requiredAction: "view" },
    ],
  },
  {
    // No "inventory" backend resource — real resources are
    // warehouse_stock, inventory_ledger, stock_adjustments,
    // stock_transfers, goods_receipts, plus "warehouses" for the
    // warehouse-master page.
    label: "Inventory",
    icon: Warehouse,
    module: ["warehouse_stock", "inventory_ledger", "stock_adjustments", "stock_transfers", "goods_receipts", "warehouses"],
    requiredAction: "view",
    children: [
      { label: "Stock Overview", href: "/dashboard/inventory", icon: Boxes, module: "warehouse_stock", requiredAction: "view" },
      { label: "Warehouse", href: "/dashboard/inventory/warehouse", icon: Warehouse, module: "warehouses", requiredAction: "view" },
      { label: "Stock Movement", href: "/dashboard/inventory/movement", icon: ClipboardList, module: "inventory_ledger", requiredAction: "view" },
      { label: "Stock Transfer", href: "/dashboard/inventory/transfer", icon: ArrowLeftRight, module: "stock_transfers", requiredAction: "view" },
      { label: "Stock Adjustment", href: "/dashboard/inventory/adjustment", icon: ClipboardCheck, module: "stock_adjustments", requiredAction: "edit" },
      { label: "Stock Count", href: "/dashboard/inventory/count", icon: ClipboardList, module: "stock_adjustments", requiredAction: "edit", releaseStatus: "backend-gap" },
      { label: "Barcode Scanner", href: "/dashboard/inventory/scanner", icon: ScanBarcode, module: "warehouse_stock", requiredAction: "view", releaseStatus: "backend-gap" },
      { label: "Reports", href: "/dashboard/inventory/reports", icon: FileBarChart, module: "reports", requiredAction: "view", releaseStatus: "backend-gap" },
    ],
  },
  {
    // No "purchase" backend resource — real resources are purchase_orders,
    // suppliers, goods_receipts, payments.
    label: "Purchase",
    icon: Truck,
    module: ["purchase_orders", "purchase_requests", "purchase_rfqs", "supplier_quotations", "suppliers"],
    requiredAction: "view",
    children: [
      { label: "Dashboard", href: "/dashboard/purchase", icon: LayoutDashboard, module: "purchase_orders", requiredAction: "view" },
      { label: "Suppliers", href: "/dashboard/purchase/suppliers", icon: Building2, module: "suppliers", requiredAction: "view" },
      { label: "Purchase Request", href: "/dashboard/purchase/request", icon: FileText, module: "purchase_requests", requiredAction: "create" },
      { label: "RFQ & Quotations", href: "/dashboard/purchase/rfq", icon: ScrollText, module: ["purchase_rfqs", "supplier_quotations", "purchase_requests"], requiredAction: "view" },
      { label: "Purchase Orders", href: "/dashboard/purchase/orders", icon: ClipboardList, module: "purchase_orders", requiredAction: "view" },
      { label: "Goods Receipt", href: "/dashboard/purchase/receipt", icon: PackageCheck, module: "goods_receipts", requiredAction: "edit" },
      { label: "Purchase Invoice", href: "/dashboard/purchase/invoice", icon: FileSpreadsheet, module: "purchase_orders", requiredAction: "view" },
      { label: "Supplier Payment", href: "/dashboard/purchase/payment", icon: Wallet, module: "payments", requiredAction: "approve" },
      { label: "Purchase Return", href: "/dashboard/purchase/return", icon: ReturnIcon, module: "purchase_orders", requiredAction: "edit" },
      { label: "Reports", href: "/dashboard/purchase/reports", icon: FileBarChart, module: "reports", requiredAction: "view", releaseStatus: "partial" },
    ],
  },
  {
    label: "Reports",
    icon: BarChart3,
    module: "reports",
    requiredAction: "view",
    children: [
      { label: "Dashboard", href: "/dashboard/reports/dashboard", icon: LayoutDashboard, module: "reports", requiredAction: "view", releaseStatus: "backend-gap" },
      { label: "Sales Reports", href: "/dashboard/reports/sales", icon: LineChart, module: "reports", requiredAction: "view", releaseStatus: "backend-gap" },
      { label: "Inventory Reports", href: "/dashboard/reports/inventory", icon: Warehouse, module: "reports", requiredAction: "view", releaseStatus: "backend-gap" },
      { label: "Purchase Reports", href: "/dashboard/reports/purchase", icon: Truck, module: "reports", requiredAction: "view", releaseStatus: "partial" },
      { label: "Customer Reports", href: "/dashboard/reports/customer", icon: Users, module: "reports", requiredAction: "view", releaseStatus: "backend-gap" },
      { label: "Financial Reports", href: "/dashboard/reports/finance", icon: Landmark, module: "reports", requiredAction: "approve", releaseStatus: "partial" },
      { label: "Product Reports", href: "/dashboard/reports/products", icon: Package, module: "reports", requiredAction: "view", releaseStatus: "backend-gap" },
      { label: "Scheduled Reports", href: "/dashboard/reports/scheduled", icon: CalendarClock, module: "reports", requiredAction: "manage", releaseStatus: "backend-gap" },
    ],
  },
  {
    // No "accounting" backend resource — real resources are accounts,
    // journal_entries, general_ledger, trial_balance, payments, reports.
    label: "Accounting",
    icon: Landmark,
    module: ["accounts", "journal_entries", "general_ledger", "trial_balance"],
    requiredAction: "view",
    children: [
      { label: "Dashboard", href: "/dashboard/accounting", icon: LayoutDashboard, module: "reports", requiredAction: "view", releaseStatus: "partial" },
      { label: "Chart Of Accounts", href: "/dashboard/accounting/accounts", icon: BookOpen, module: "accounts", requiredAction: "view" },
      { label: "Journal Entries", href: "/dashboard/accounting/journal", icon: ScrollText, module: "journal_entries", requiredAction: "create" },
      { label: "General Ledger", href: "/dashboard/accounting/ledger", icon: FileBarChart2, module: "general_ledger", requiredAction: "view" },
      { label: "Accounts Receivable", href: "/dashboard/accounting/receivable", icon: HandCoins, module: "reports", requiredAction: "view" },
      { label: "Accounts Payable", href: "/dashboard/accounting/payable", icon: Wallet, module: "reports", requiredAction: "view" },
      { label: "Payments", href: "/dashboard/accounting/payment", icon: ReceiptText, module: "payments", requiredAction: "approve" },
      { label: "Expenses", href: "/dashboard/accounting/expense", icon: FileText, module: "journal_entries", requiredAction: "create", releaseStatus: "backend-gap" },
      { label: "Taxes", href: "/dashboard/accounting/tax", icon: Percent, module: "accounts", requiredAction: "manage", releaseStatus: "backend-gap" },
      { label: "Financial Statements", href: "/dashboard/accounting/statements", icon: FileBarChart, module: "reports", requiredAction: "approve", releaseStatus: "partial" },
      { label: "Audit Log", href: "/dashboard/accounting/audit", icon: History, module: "reports", requiredAction: "manage" },
    ],
  },
  {
    // No "hr" backend resource — real resources are employees,
    // departments, designations, attendance, leave_types, leave_requests,
    // shifts, payroll_*, employee_assignments, employee_compensations.
    label: "HR Management",
    icon: UserCog,
    module: ["employees", "departments", "attendance", "leave_requests"],
    requiredAction: "view",
    children: [
      { label: "Dashboard", href: "/dashboard/hr", icon: LayoutDashboard, module: "employees", requiredAction: "view", releaseStatus: "partial" },
      { label: "Employees", href: "/dashboard/hr/employees", icon: Users, module: "employees", requiredAction: "view" },
      { label: "Organization", href: "/dashboard/hr/organization", icon: Network, module: "departments", requiredAction: "view", releaseStatus: "backend-gap" },
      { label: "Departments", href: "/dashboard/hr/departments", icon: Building, module: "departments", requiredAction: "view" },
      { label: "Attendance", href: "/dashboard/hr/attendance", icon: CalendarCheck, module: "attendance", requiredAction: "view" },
      { label: "Shift Management", href: "/dashboard/hr/shifts", icon: Clock, module: "shifts", requiredAction: "edit", releaseStatus: "backend-gap" },
      { label: "Leave Management", href: "/dashboard/hr/leaves", icon: CalendarRange, module: "leave_requests", requiredAction: "view" },
      { label: "Payroll", href: "/dashboard/hr/payroll", icon: Banknote, module: ["payroll_periods", "payroll_runs", "payroll_components", "payroll_configuration"], requiredAction: "view" },
      { label: "Employee Self Service", href: "/dashboard/hr/ess", icon: UserCircle, module: "employees", requiredAction: "view", releaseStatus: "partial" },
      { label: "Performance", href: "/dashboard/hr/performance", icon: Target, module: "employees", requiredAction: "edit", releaseStatus: "backend-gap" },
      { label: "HR Reports", href: "/dashboard/hr/reports", icon: FileBarChart, module: "reports", requiredAction: "view", releaseStatus: "backend-gap" },
    ],
  },
  {
    // No "admin" backend resource — real resources are users, roles,
    // permissions, companies, branches, notifications, webhooks.
    label: "Administration",
    icon: ShieldCheck,
    module: ["users", "roles", "companies", "branches"],
    requiredAction: "manage",
    children: [
      { label: "Dashboard", href: "/dashboard/admin", icon: LayoutDashboard, module: "users", requiredAction: "view", releaseStatus: "backend-gap" },
      { label: "User Management", href: "/dashboard/admin/users", icon: Users, module: "users", requiredAction: "manage" },
      { label: "Roles", href: "/dashboard/admin/roles", icon: UserCog, module: "roles", requiredAction: "manage" },
      { label: "Permissions", href: "/dashboard/admin/permissions", icon: KeyRound, module: "permissions", requiredAction: "manage" },
      { label: "Company Management", href: "/dashboard/admin/company", icon: Building2, module: "companies", requiredAction: "manage" },
      { label: "Branch Management", href: "/dashboard/admin/branches", icon: Store, module: "branches", requiredAction: "manage" },
      { label: "Workflow Builder", href: "/dashboard/admin/workflows", icon: Workflow, module: "users", requiredAction: "manage", releaseStatus: "backend-gap" },
      { label: "Notification Center", href: "/dashboard/admin/notifications", icon: BellRing, module: "notifications", requiredAction: "view" },
      { label: "Audit Logs", href: "/dashboard/admin/audit", icon: History, module: "users", requiredAction: "view", releaseStatus: "backend-gap" },
      { label: "Integrations", href: "/dashboard/admin/integrations", icon: Plug, module: "webhooks", requiredAction: "view" },
      { label: "Security", href: "/dashboard/admin/security", icon: Lock, module: "users", requiredAction: "manage", releaseStatus: "backend-gap" },
      { label: "System Settings", href: "/dashboard/admin/settings", icon: Settings, module: "settings", requiredAction: "manage", releaseStatus: "backend-gap" },
    ],
  },
  {
    label: "Settings",
    href: "/dashboard/settings",
    icon: Settings,
    module: "settings",
    requiredAction: "view",
  },
]
