import type {
  GoodsReceipt,
  ProductCostPoint,
  PurchaseInvoice,
  PurchaseOrder,
  PurchaseRequest,
  PurchaseReturn,
  PurchaseTrendPoint,
  Supplier,
  SupplierPayment,
  SupplierPerformance,
} from "../types"

const now = Date.now()
const daysAgo = (n: number) => new Date(now - n * 86400000).toISOString()
const daysFromNow = (n: number) => new Date(now + n * 86400000).toISOString()

export const mockSuppliers: Supplier[] = [
  {
    id: "sup-1",
    name: "Nike Apparel Co.",
    code: "SUP-001",
    type: "manufacturer",
    status: "active",
    contactPerson: "John Carter",
    phone: "+1 503 555 0142",
    email: "john.carter@nikeapparel.example",
    website: "https://nikeapparel.example",
    address: "1 Bowerman Dr, Beaverton, OR",
    country: "USA",
    taxId: "US-9834-2201",
    paymentTerms: "Net 30",
    currency: "USD",
    bankAccount: "****4821",
    totalPurchase: 185000,
    outstanding: 32000,
  },
  {
    id: "sup-2",
    name: "Zara Textile Group",
    code: "SUP-002",
    type: "wholesaler",
    status: "active",
    contactPerson: "Elena Ruiz",
    phone: "+34 91 555 0198",
    email: "elena.ruiz@zaratextile.example",
    address: "Av. de la Diputación, A Coruña",
    country: "Spain",
    taxId: "ES-B1234567",
    paymentTerms: "Net 45",
    currency: "EUR",
    bankAccount: "****2290",
    totalPurchase: 98000,
    outstanding: 15500,
  },
  {
    id: "sup-3",
    name: "Bangkok Fabric Mills",
    code: "SUP-003",
    type: "distributor",
    status: "active",
    contactPerson: "Somchai Preecha",
    phone: "+66 2 555 0173",
    email: "somchai@bkfabricmills.example",
    address: "Sukhumvit Rd, Bangkok",
    country: "Thailand",
    paymentTerms: "Net 15",
    currency: "THB",
    totalPurchase: 42000,
    outstanding: 8200,
  },
  {
    id: "sup-4",
    name: "H&M Sourcing Partner",
    code: "SUP-004",
    type: "agent",
    status: "inactive",
    contactPerson: "Anna Lindqvist",
    phone: "+46 8 555 0110",
    email: "anna.l@hmsourcing.example",
    address: "Mäster Samuelsgatan, Stockholm",
    country: "Sweden",
    paymentTerms: "Net 30",
    currency: "SEK",
    totalPurchase: 25000,
    outstanding: 0,
  },
]

export const mockSupplierPerformance: Record<string, SupplierPerformance> = {
  "sup-1": { avgDeliveryDays: 6, orderAccuracy: 97, qualityRating: 4.6, purchaseVolume: 185000 },
  "sup-2": { avgDeliveryDays: 10, orderAccuracy: 92, qualityRating: 4.2, purchaseVolume: 98000 },
  "sup-3": { avgDeliveryDays: 14, orderAccuracy: 88, qualityRating: 3.9, purchaseVolume: 42000 },
  "sup-4": { avgDeliveryDays: 21, orderAccuracy: 85, qualityRating: 3.7, purchaseVolume: 25000 },
}

export const mockPurchaseRequests: PurchaseRequest[] = [
  {
    id: "pr-1",
    reference: "PR-2026-0031",
    department: "Retail Operations",
    requester: "Store Manager",
    requiredDate: daysFromNow(14),
    status: "approved",
    items: [
      {
        id: "pri-1",
        productId: "prod-1",
        productName: "Nike Classic Tee",
        sku: "NIKE-TS-BLK-M-001",
        color: "Black",
        size: "M",
        quantity: 200,
        reason: "Restock — low inventory at Yangon Warehouse",
      },
    ],
    notes: "Priority restock ahead of spring collection launch.",
    createdAt: daysAgo(6),
  },
  {
    id: "pr-2",
    reference: "PR-2026-0032",
    department: "Merchandising",
    requester: "Purchase Staff",
    requiredDate: daysFromNow(21),
    status: "submitted",
    items: [
      {
        id: "pri-2",
        productId: "prod-2",
        productName: "Floral Summer Dress",
        sku: "ZARA-FD-RED-S-014",
        color: "Red",
        size: "S",
        quantity: 80,
        reason: "New summer collection demand forecast",
      },
    ],
    createdAt: daysAgo(2),
  },
  {
    id: "pr-3",
    reference: "PR-2026-0033",
    department: "Retail Operations",
    requester: "Warehouse Staff",
    requiredDate: daysFromNow(7),
    status: "draft",
    items: [
      {
        id: "pri-3",
        productId: "prod-4",
        productName: "Leather Belt",
        sku: "GUESS-AC-007",
        quantity: 150,
        reason: "Accessory line replenishment",
      },
    ],
    createdAt: daysAgo(0),
  },
]

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: "po-1",
    poNumber: "PO-2026-0110",
    supplierId: "sup-1",
    supplierName: "Nike Apparel Co.",
    contact: "John Carter",
    paymentTerms: "Net 30",
    date: daysAgo(10),
    deliveryDate: daysFromNow(4),
    status: "partially_received",
    items: [
      {
        id: "poi-1",
        productId: "prod-1",
        productName: "Nike Classic Tee",
        sku: "NIKE-TS-BLK-M-001",
        color: "Black",
        size: "M",
        quantity: 200,
        unitCost: 20,
        discount: 200,
        tax: 320,
        amount: 4120,
      },
    ],
    subtotal: 4000,
    taxTotal: 320,
    discountTotal: 200,
    grandTotal: 4120,
    createdBy: "Purchase Staff",
  },
  {
    id: "po-2",
    poNumber: "PO-2026-0111",
    supplierId: "sup-2",
    supplierName: "Zara Textile Group",
    contact: "Elena Ruiz",
    paymentTerms: "Net 45",
    date: daysAgo(5),
    deliveryDate: daysFromNow(10),
    status: "approved",
    items: [
      {
        id: "poi-2",
        productId: "prod-2",
        productName: "Floral Summer Dress",
        sku: "ZARA-FD-RED-S-014",
        color: "Red",
        size: "S",
        quantity: 80,
        unitCost: 30,
        discount: 0,
        tax: 192,
        amount: 2592,
      },
    ],
    subtotal: 2400,
    taxTotal: 192,
    discountTotal: 0,
    grandTotal: 2592,
    createdBy: "Purchase Manager",
  },
  {
    id: "po-3",
    poNumber: "PO-2026-0112",
    supplierId: "sup-3",
    supplierName: "Bangkok Fabric Mills",
    contact: "Somchai Preecha",
    paymentTerms: "Net 15",
    date: daysAgo(2),
    deliveryDate: daysFromNow(20),
    status: "pending_approval",
    items: [
      {
        id: "poi-3",
        productId: "prod-4",
        productName: "Leather Belt",
        sku: "GUESS-AC-007",
        quantity: 150,
        unitCost: 12,
        discount: 90,
        tax: 129.6,
        amount: 1839.6,
      },
    ],
    subtotal: 1800,
    taxTotal: 129.6,
    discountTotal: 90,
    grandTotal: 1839.6,
    createdBy: "Purchase Staff",
  },
  {
    id: "po-4",
    poNumber: "PO-2026-0113",
    supplierId: "sup-1",
    supplierName: "Nike Apparel Co.",
    contact: "John Carter",
    paymentTerms: "Net 30",
    date: daysAgo(30),
    deliveryDate: daysAgo(20),
    status: "received",
    items: [
      {
        id: "poi-4",
        productId: "prod-1",
        productName: "Nike Classic Tee",
        sku: "NIKE-TS-BLK-L-001",
        color: "Black",
        size: "L",
        quantity: 100,
        unitCost: 20,
        discount: 0,
        tax: 160,
        amount: 2160,
      },
    ],
    subtotal: 2000,
    taxTotal: 160,
    discountTotal: 0,
    grandTotal: 2160,
    createdBy: "Purchase Manager",
  },
]

export const mockGoodsReceipts: GoodsReceipt[] = [
  {
    id: "grn-1",
    reference: "GRN-2026-0056",
    purchaseOrderId: "po-1",
    poNumber: "PO-2026-0110",
    supplierId: "sup-1",
    supplierName: "Nike Apparel Co.",
    warehouseId: "wh-yangon",
    warehouseName: "Yangon Warehouse",
    status: "confirmed",
    items: [
      {
        id: "gri-1",
        productId: "prod-1",
        productName: "Nike Classic Tee",
        sku: "NIKE-TS-BLK-M-001",
        color: "Black",
        size: "M",
        orderedQty: 200,
        receivedQty: 150,
        rejectedQty: 5,
      },
    ],
    receivedBy: "Warehouse Staff",
    receivedAt: daysAgo(3),
  },
  {
    id: "grn-2",
    reference: "GRN-2026-0057",
    purchaseOrderId: "po-4",
    poNumber: "PO-2026-0113",
    supplierId: "sup-1",
    supplierName: "Nike Apparel Co.",
    warehouseId: "wh-yangon",
    warehouseName: "Yangon Warehouse",
    status: "confirmed",
    items: [
      {
        id: "gri-2",
        productId: "prod-1",
        productName: "Nike Classic Tee",
        sku: "NIKE-TS-BLK-L-001",
        color: "Black",
        size: "L",
        orderedQty: 100,
        receivedQty: 100,
        rejectedQty: 0,
      },
    ],
    receivedBy: "Warehouse Staff",
    receivedAt: daysAgo(20),
  },
]

export const mockInvoices: PurchaseInvoice[] = [
  {
    id: "inv-p-1",
    invoiceNumber: "PINV-2026-0201",
    supplierId: "sup-1",
    supplierName: "Nike Apparel Co.",
    purchaseOrderId: "po-1",
    poNumber: "PO-2026-0110",
    items: mockPurchaseOrders[0].items,
    subtotal: 4000,
    taxTotal: 320,
    discountTotal: 200,
    grandTotal: 4120,
    amountPaid: 2000,
    paymentStatus: "partial",
    dueDate: daysFromNow(20),
    issuedAt: daysAgo(9),
  },
  {
    id: "inv-p-2",
    invoiceNumber: "PINV-2026-0202",
    supplierId: "sup-1",
    supplierName: "Nike Apparel Co.",
    purchaseOrderId: "po-4",
    poNumber: "PO-2026-0113",
    items: mockPurchaseOrders[3].items,
    subtotal: 2000,
    taxTotal: 160,
    discountTotal: 0,
    grandTotal: 2160,
    amountPaid: 2160,
    paymentStatus: "paid",
    dueDate: daysAgo(5),
    issuedAt: daysAgo(29),
  },
  {
    id: "inv-p-3",
    invoiceNumber: "PINV-2026-0203",
    supplierId: "sup-2",
    supplierName: "Zara Textile Group",
    purchaseOrderId: "po-2",
    poNumber: "PO-2026-0111",
    items: mockPurchaseOrders[1].items,
    subtotal: 2400,
    taxTotal: 192,
    discountTotal: 0,
    grandTotal: 2592,
    amountPaid: 0,
    paymentStatus: "unpaid",
    dueDate: daysFromNow(35),
    issuedAt: daysAgo(4),
  },
  {
    id: "inv-p-4",
    invoiceNumber: "PINV-2026-0198",
    supplierId: "sup-3",
    supplierName: "Bangkok Fabric Mills",
    purchaseOrderId: "po-3",
    poNumber: "PO-2026-0112",
    items: mockPurchaseOrders[2].items,
    subtotal: 1800,
    taxTotal: 129.6,
    discountTotal: 90,
    grandTotal: 1839.6,
    amountPaid: 0,
    paymentStatus: "overdue",
    dueDate: daysAgo(3),
    issuedAt: daysAgo(18),
  },
]

export const mockPayments: SupplierPayment[] = [
  {
    id: "pay-1",
    reference: "PMT-2026-0071",
    supplierId: "sup-1",
    supplierName: "Nike Apparel Co.",
    invoiceId: "inv-p-1",
    invoiceNumber: "PINV-2026-0201",
    paymentDate: daysAgo(5),
    amount: 2000,
    method: "bank_transfer",
    referenceNumber: "TXN-88213",
    notes: "Partial payment",
  },
  {
    id: "pay-2",
    reference: "PMT-2026-0072",
    supplierId: "sup-1",
    supplierName: "Nike Apparel Co.",
    invoiceId: "inv-p-2",
    invoiceNumber: "PINV-2026-0202",
    paymentDate: daysAgo(25),
    amount: 2160,
    method: "bank_transfer",
    referenceNumber: "TXN-87950",
  },
]

export const mockReturns: PurchaseReturn[] = [
  {
    id: "ret-1",
    reference: "RTN-P-2026-0012",
    supplierId: "sup-1",
    supplierName: "Nike Apparel Co.",
    purchaseOrderId: "po-1",
    poNumber: "PO-2026-0110",
    reason: "damaged_product",
    status: "approved",
    items: [
      {
        id: "reti-1",
        productId: "prod-1",
        productName: "Nike Classic Tee",
        sku: "NIKE-TS-BLK-M-001",
        color: "Black",
        size: "M",
        quantity: 5,
        unitCost: 20,
      },
    ],
    notes: "Received with visible stitching defects.",
    createdAt: daysAgo(2),
  },
]

export const purchaseTrend: PurchaseTrendPoint[] = [
  { period: "Feb", amount: 62000 },
  { period: "Mar", amount: 58000 },
  { period: "Apr", amount: 71000 },
  { period: "May", amount: 65000 },
  { period: "Jun", amount: 80000 },
  { period: "Jul", amount: 74000 },
]

export const productCostAnalysis: ProductCostPoint[] = [
  { productName: "Nike Classic Tee", previousCost: 18, currentCost: 20, costChangePercent: 11.1, supplierName: "Nike Apparel Co." },
  { productName: "Floral Summer Dress", previousCost: 32, currentCost: 30, costChangePercent: -6.3, supplierName: "Zara Textile Group" },
  { productName: "Leather Belt", previousCost: 11, currentCost: 12, costChangePercent: 9.1, supplierName: "Bangkok Fabric Mills" },
]
