import {
  LayoutDashboard,
  ShoppingCart,
  Receipt,
  Undo2,
  Shirt,
  Tags,
  Award,
  Ruler,
  Palette,
  Warehouse,
  Boxes,
  ArrowLeftRight,
  ClipboardList,
  ClipboardCheck,
  ScanBarcode,
  FileBarChart,
  Truck,
  Building2,
  FileText,
  PackageCheck,
  FileSpreadsheet,
  Wallet,
  Undo2 as ReturnIcon,
  Users,
  Tag,
  Gift,
  BarChart3,
  LineChart,
  Package,
  Landmark,
  CalendarClock,
  BookOpen,
  ScrollText,
  HandCoins,
  ReceiptText,
  Percent,
  FileBarChart2,
  History,
  Settings,
  UserCog,
  Network,
  Building,
  CalendarCheck,
  Clock,
  CalendarRange,
  Banknote,
  UserCircle,
  Target,
  ShieldCheck,
  Lock,
  KeyRound,
  Workflow,
  BellRing,
  Store,
  Plug,
} from "lucide-react"
import type { NavItem } from "@/types/navigation"

/**
 * Single source of truth for the sidebar's navigation tree.
 * `module` maps each item to a permission-module key (types/user.ts) —
 * the Sidebar component filters this tree against the current user's
 * permissions before rendering, per Design System §4's "omission over
 * denial" rule: a user without access simply never sees the item.
 */
export const navigationTree: NavItem[] = [
  {
    label: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
    module: "dashboard",
    requiredAction: "view",
  },
  {
    label: "Sales",
    icon: Receipt,
    module: "sales",
    requiredAction: "view",
    children: [
      { label: "Dashboard", href: "/dashboard/sales", icon: LayoutDashboard, module: "sales", requiredAction: "view" },
      { label: "POS", href: "/dashboard/sales/pos", icon: ShoppingCart, module: "pos", requiredAction: "view" },
      { label: "Sales Orders", href: "/dashboard/sales/orders", icon: ClipboardList, module: "sales", requiredAction: "view" },
      { label: "Sales Invoice", href: "/dashboard/sales/invoices", icon: Receipt, module: "sales", requiredAction: "view" },
      { label: "Customers", href: "/dashboard/sales/customers", icon: Users, module: "sales", requiredAction: "view" },
      { label: "Returns", href: "/dashboard/sales/returns", icon: Undo2, module: "sales", requiredAction: "edit" },
      { label: "Discounts", href: "/dashboard/sales/discounts", icon: Tag, module: "sales", requiredAction: "approve" },
      { label: "Loyalty", href: "/dashboard/sales/loyalty", icon: Gift, module: "sales", requiredAction: "view" },
      { label: "Reports", href: "/dashboard/sales/reports", icon: FileBarChart, module: "sales", requiredAction: "view" },
    ],
  },
  {
    label: "Products",
    icon: Shirt,
    module: "products",
    requiredAction: "view",
    children: [
      { label: "Product Master", href: "/dashboard/products", icon: Shirt, module: "products", requiredAction: "view" },
      { label: "Category", href: "/dashboard/products/categories", icon: Tags, module: "products", requiredAction: "view" },
      { label: "Brand", href: "/dashboard/products/brands", icon: Award, module: "products", requiredAction: "view" },
      { label: "Size", href: "/dashboard/products/sizes", icon: Ruler, module: "products", requiredAction: "view" },
      { label: "Color", href: "/dashboard/products/colors", icon: Palette, module: "products", requiredAction: "view" },
      { label: "Variant", href: "/dashboard/products/variants", icon: Boxes, module: "products", requiredAction: "view" },
    ],
  },
  {
    label: "Inventory",
    icon: Warehouse,
    module: "inventory",
    requiredAction: "view",
    children: [
      { label: "Stock Overview", href: "/dashboard/inventory", icon: Boxes, module: "inventory", requiredAction: "view" },
      { label: "Warehouse", href: "/dashboard/inventory/warehouse", icon: Warehouse, module: "inventory", requiredAction: "view" },
      { label: "Stock Movement", href: "/dashboard/inventory/movement", icon: ClipboardList, module: "inventory", requiredAction: "view" },
      { label: "Stock Transfer", href: "/dashboard/inventory/transfer", icon: ArrowLeftRight, module: "inventory", requiredAction: "view" },
      { label: "Stock Adjustment", href: "/dashboard/inventory/adjustment", icon: ClipboardCheck, module: "inventory", requiredAction: "edit" },
      { label: "Stock Count", href: "/dashboard/inventory/count", icon: ClipboardList, module: "inventory", requiredAction: "edit" },
      { label: "Barcode Scanner", href: "/dashboard/inventory/scanner", icon: ScanBarcode, module: "inventory", requiredAction: "view" },
      { label: "Reports", href: "/dashboard/inventory/reports", icon: FileBarChart, module: "inventory", requiredAction: "view" },
    ],
  },
  {
    label: "Purchase",
    icon: Truck,
    module: "purchase",
    requiredAction: "view",
    children: [
      { label: "Dashboard", href: "/dashboard/purchase", icon: LayoutDashboard, module: "purchase", requiredAction: "view" },
      { label: "Suppliers", href: "/dashboard/purchase/suppliers", icon: Building2, module: "purchase", requiredAction: "view" },
      { label: "Purchase Request", href: "/dashboard/purchase/request", icon: FileText, module: "purchase", requiredAction: "create" },
      { label: "Purchase Orders", href: "/dashboard/purchase/orders", icon: ClipboardList, module: "purchase", requiredAction: "view" },
      { label: "Goods Receipt", href: "/dashboard/purchase/receipt", icon: PackageCheck, module: "purchase", requiredAction: "edit" },
      { label: "Purchase Invoice", href: "/dashboard/purchase/invoice", icon: FileSpreadsheet, module: "purchase", requiredAction: "view" },
      { label: "Supplier Payment", href: "/dashboard/purchase/payment", icon: Wallet, module: "purchase", requiredAction: "approve" },
      { label: "Purchase Return", href: "/dashboard/purchase/return", icon: ReturnIcon, module: "purchase", requiredAction: "edit" },
      { label: "Reports", href: "/dashboard/purchase/reports", icon: FileBarChart, module: "purchase", requiredAction: "view" },
    ],
  },
  {
    label: "Reports",
    icon: BarChart3,
    module: "reports",
    requiredAction: "view",
    children: [
      { label: "Dashboard", href: "/dashboard/reports/dashboard", icon: LayoutDashboard, module: "reports", requiredAction: "view" },
      { label: "Sales Reports", href: "/dashboard/reports/sales", icon: LineChart, module: "reports", requiredAction: "view" },
      { label: "Inventory Reports", href: "/dashboard/reports/inventory", icon: Warehouse, module: "reports", requiredAction: "view" },
      { label: "Purchase Reports", href: "/dashboard/reports/purchase", icon: Truck, module: "reports", requiredAction: "view" },
      { label: "Customer Reports", href: "/dashboard/reports/customer", icon: Users, module: "reports", requiredAction: "view" },
      { label: "Financial Reports", href: "/dashboard/reports/finance", icon: Landmark, module: "reports", requiredAction: "approve" },
      { label: "Product Reports", href: "/dashboard/reports/products", icon: Package, module: "reports", requiredAction: "view" },
      { label: "Scheduled Reports", href: "/dashboard/reports/scheduled", icon: CalendarClock, module: "reports", requiredAction: "manage" },
    ],
  },
  {
    label: "Accounting",
    icon: Landmark,
    module: "accounting",
    requiredAction: "view",
    children: [
      { label: "Dashboard", href: "/dashboard/accounting", icon: LayoutDashboard, module: "accounting", requiredAction: "view" },
      { label: "Chart Of Accounts", href: "/dashboard/accounting/accounts", icon: BookOpen, module: "accounting", requiredAction: "view" },
      { label: "Journal Entries", href: "/dashboard/accounting/journal", icon: ScrollText, module: "accounting", requiredAction: "create" },
      { label: "General Ledger", href: "/dashboard/accounting/ledger", icon: FileBarChart2, module: "accounting", requiredAction: "view" },
      { label: "Accounts Receivable", href: "/dashboard/accounting/receivable", icon: HandCoins, module: "accounting", requiredAction: "view" },
      { label: "Accounts Payable", href: "/dashboard/accounting/payable", icon: Wallet, module: "accounting", requiredAction: "view" },
      { label: "Payments", href: "/dashboard/accounting/payment", icon: ReceiptText, module: "accounting", requiredAction: "approve" },
      { label: "Expenses", href: "/dashboard/accounting/expense", icon: FileText, module: "accounting", requiredAction: "create" },
      { label: "Taxes", href: "/dashboard/accounting/tax", icon: Percent, module: "accounting", requiredAction: "manage" },
      { label: "Financial Statements", href: "/dashboard/accounting/statements", icon: FileBarChart, module: "accounting", requiredAction: "approve" },
      { label: "Audit Log", href: "/dashboard/accounting/audit", icon: History, module: "accounting", requiredAction: "manage" },
    ],
  },
  {
    label: "HR Management",
    icon: UserCog,
    module: "hr",
    requiredAction: "view",
    children: [
      { label: "Dashboard", href: "/dashboard/hr", icon: LayoutDashboard, module: "hr", requiredAction: "view" },
      { label: "Employees", href: "/dashboard/hr/employees", icon: Users, module: "hr", requiredAction: "view" },
      { label: "Organization", href: "/dashboard/hr/organization", icon: Network, module: "hr", requiredAction: "view" },
      { label: "Departments", href: "/dashboard/hr/departments", icon: Building, module: "hr", requiredAction: "view" },
      { label: "Attendance", href: "/dashboard/hr/attendance", icon: CalendarCheck, module: "hr", requiredAction: "view" },
      { label: "Shift Management", href: "/dashboard/hr/shifts", icon: Clock, module: "hr", requiredAction: "edit" },
      { label: "Leave Management", href: "/dashboard/hr/leaves", icon: CalendarRange, module: "hr", requiredAction: "view" },
      { label: "Payroll", href: "/dashboard/hr/payroll", icon: Banknote, module: "hr", requiredAction: "approve" },
      { label: "Employee Self Service", href: "/dashboard/hr/ess", icon: UserCircle, module: "hr", requiredAction: "view" },
      { label: "Performance", href: "/dashboard/hr/performance", icon: Target, module: "hr", requiredAction: "edit" },
      { label: "HR Reports", href: "/dashboard/hr/reports", icon: FileBarChart, module: "hr", requiredAction: "view" },
    ],
  },
  {
    label: "Administration",
    icon: ShieldCheck,
    module: "admin",
    requiredAction: "manage",
    children: [
      { label: "Dashboard", href: "/dashboard/admin", icon: LayoutDashboard, module: "admin", requiredAction: "view" },
      { label: "User Management", href: "/dashboard/admin/users", icon: Users, module: "admin", requiredAction: "manage" },
      { label: "Roles", href: "/dashboard/admin/roles", icon: UserCog, module: "admin", requiredAction: "manage" },
      { label: "Permissions", href: "/dashboard/admin/permissions", icon: KeyRound, module: "admin", requiredAction: "manage" },
      { label: "Company Management", href: "/dashboard/admin/company", icon: Building2, module: "admin", requiredAction: "manage" },
      { label: "Branch Management", href: "/dashboard/admin/branches", icon: Store, module: "admin", requiredAction: "manage" },
      { label: "Workflow Builder", href: "/dashboard/admin/workflows", icon: Workflow, module: "admin", requiredAction: "manage" },
      { label: "Notification Center", href: "/dashboard/admin/notifications", icon: BellRing, module: "admin", requiredAction: "view" },
      { label: "Audit Logs", href: "/dashboard/admin/audit", icon: History, module: "admin", requiredAction: "view" },
      { label: "Integrations", href: "/dashboard/admin/integrations", icon: Plug, module: "admin", requiredAction: "manage" },
      { label: "Security", href: "/dashboard/admin/security", icon: Lock, module: "admin", requiredAction: "manage" },
      { label: "System Settings", href: "/dashboard/admin/settings", icon: Settings, module: "admin", requiredAction: "manage" },
    ],
  },
  {
    label: "Settings",
    href: "/dashboard/settings",
    icon: Settings,
    module: "settings",
    requiredAction: "view",
  },
]
